---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgDS9UvWHTfTRz7ZtHGgoGgiJwIys52YWu1dhBMQwii0YHKL8VkX+Qu8vuoyo6mRSr/S79dz99elbqO/e/IatnBTDyX9TcSxF2e+ytrQZkXFCNt2s2zJNjOy1FSc1R2gZCRoaZ2ETixP36cr222ou0r+x4RYhtVnIIci7C/nZ5vTlKf4bPnrAHVcWWwk9jjc+Us6B2XlABmYM+ydhk3X9vEAeNnhEXgP4n6qneDarKTUqxksj+7lqeRrNfSFmuDxwJzOqG5Q/xN2apz0SLGmOjd4JQZ9T2ByqYUZ7I3mOennHhepHmQfd9olneu8DuahrqgXMpZisVndZPb2rW17Ep60skDtcqtbtLSZfriTk2DTL6TD8GAemImtRYmRwB94FVDW04b5KrCfXqg0zhNio1iSvJD2Cd9Os9OIXkQAFeMk2YBysvPelr2uJ2g/bZi7b1CA1y1Avjo0trYg46hNQ+AEuTNAcKEMkOl2fAJeXNEvAMcsiHLJ1Ner18U90PMFHcqh8cAjHFGnGZl94/wSd7FaoB5m7s4WT1g1ajmX7LXy2SsKcAk/PIiYQPNpw4UMRZ0KNGog+cNuxsRoeh833gIYzE3LVf3RjVQuM8Gpo+baTcYMxVEPo1m1tnHYA+JIz5/TOuNAO7QJ4i/ZXW57EohFsA1EpAs6AYpVG9BIgz2Chi3+JXp91TuM6m+MbNhxr24mz2+88hadcQn4dzMAp9NQHhJknCzAUUGUsv4beQ28bUQ=
    password: AgDJeMjqzMf352dgvjnuTHLawQXDpgXUTtYGQlm7cH/sLyCIM2Ej358RV0LT+aFJUl+AmxVa3Mi23Yl/YXzlJtjMAJso7KCMqfO8aXRvejEiYWOHTmfZdutKtT90DZYwlXt8GPWYVcvMsHcFaU6Q/7HFoMBblxFeGXyRafFmjj2RJw0MNZuadRRtfUn3c4Mopgs+uCc+Kor8fb1fJIfjImppPGfYGWqEnGHVsDQyJIzZTK9ss/moVFBPbIn5hyzndTnLKuZvVSd++3GnLzkpdcRr5Du2XLt7MnKPlranXBarYJN2hfgvvfLk8mjAXgaBzYvZeWV07Ohug1zkFj2xnPBG2mDsi0EyVPQGlYyyXWzLS1LZJQuLQ171PPwZ9SlXiM4MeVbjuR46ebbJXpfuFKrx5RZvqxinYLmRvkc6MZUW0pkKnNkuRke6vT5YqSxGI+MYTfLH2q3zXD0Ar9HKnJaBjIx183xD4R5i610N9e2dgSVXb/FjbffBj1WnOAMqlByVBYV77FmPXBCGmplSU9fhwQzo0t1IxZQ0iPoKq/OzJOk49+1vefsjdjZtkdAklLlYlA+mn/EuNauzFwEmNYlxkNoWSwEbSa9Q35b8o87RrD3ZiI63FIyYD/XiMV3I5p9fH2u5OOieoLMDT3lVJzF4E5SPEk0U1LNsworT3VwqwhvdAoWlCeh1Yg8vfJvRUQLkBUx1XAoc/TsgyPTgaBE=
    username: AgAb3qQkBJMLyTlu/Z2arjH4LRUX0k5XSl+3Tu614B+KuEJL5KAqLNpq7wUXn0PZiW+yPOAjM9hJ0sm6Nn7GQC/tZak7jfXDMX6UAowoem/xrnOp6Rx1xXTDqiq3HGy76Z99smFV9yPT9v0xb2qoxvJJ0XXlEBptK+sG5mxA2nPvNxjTxvbMkvd1D/ApLj39vLujwl3b44EqdWNlMgVof//QO8Nyr2Qq+nXzfHUW7+P7qqaN8gDv53cLK5UHyJpFGHtbv/C98SLUAr6W+G4d5y4fpa0T9+0ycnrG17eOTkB6RF3gmICtDdLZclawtw2yFoTk9JeFPZAydUqsFrIKe8uUfUjDEZy1H8cII77MKTzQvPzEL8uhnEtKzfHAqK5dRfPtIe4G6xoridACCasT9kTGkfFiE8GoSzL+6v/r/n00TIPqw94g8bkd+3mVwSiOtQ1JwMgVxO7B5lIetnMY6fscgn6ho9LmV+2Dkb96v/jnUSPvvQ9OmVncNIo+QnhWT7VuMYIB0jEQJPy0pJgB3gq1UejsWHiu+OCOps04NeutaRKNd452Qenpk3U4t2myhexfQvb51grdSh6MvUB27elrSo4we2LBRmkAdpigLQXqdhB7fue1Gki1ouggFeKTlyPP5V3rXSntiQxmPFBP9FGN7isHi6/kzOI2FIJy60ONu6htUML4Ud5zd4sKjkgqb3eK58tvxd5nBpZfqg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque


